In [193]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
%matplotlib inline
print('Done!')

Done!

In [194]:
housing_train_data = pd.read_csv('C:\\Users\\Auditor\\Desktop\\Victor\\New folder\\Data Science\\Projects\\House Prices - Advanced Regression Techniques\\Train.csv')

In [195]:
housing_test_data = pd.read_csv('C:\\Users\\Auditor\\Desktop\\Victor\\New folder\\Data Science\\Projects\\House Prices - Advanced Regression Techniques\\Test.csv')

In [196]:
housing_train_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [197]:
housing_test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [198]:
#We are going to create a pipeline that in one go: fills null values, drops unwanted columns and gets dummies/ one_hot_encoder

In [199]:
#Changing all null numeric values to mean

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer

class MultipleColumnImputerMean(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns):
        self.columns = columns
    
    def fit(self, X, y=None):
        self.imputer = SimpleImputer(strategy='mean')
        self.imputer.fit(X[self.columns])
        return self
    
    def transform(self, X):
        X_copy = X.copy()
        X_copy[self.columns] = self.imputer.transform(X_copy[self.columns])
        return X_copy

In [200]:
#Changing all null string values to mode

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer

class MultipleColumnImputerMode(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns):
        self.columns = columns
    
    def fit(self, X, y=None):
        self.imputer = SimpleImputer(strategy='most_frequent')
        self.imputer.fit(X[self.columns])
        return self
    
    def transform(self, X):
        X_copy = X.copy()
        X_copy[self.columns] = self.imputer.transform(X_copy[self.columns])
        return X_copy

In [201]:
#gets dummies/ one_hot_encoder
class GetDummies(BaseEstimator, TransformerMixin):
    
    def __init__(self, column_names):
        self.column_names = column_names

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        columns = X[self.column_names]  # Extract the specified columns

        # Apply one-hot encoding to each specified column
        dummies_list = [pd.get_dummies(columns[col], prefix=col) for col in self.column_names]

        # Concatenate one-hot encoded columns with the original DataFrame and delete dummied column
        X_encoded = pd.concat([X] + dummies_list, axis=1).drop(self.column_names, axis=1)

        return X_encoded

In [202]:
#Create a pipeline

In [203]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('MultipleColumnImputerMean', MultipleColumnImputerMean(columns=['LotFrontage', 'MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','BsmtFullBath','BsmtHalfBath','GarageYrBlt','GarageCars','GarageArea'])),
    ('MultipleColumnImputerMode', MultipleColumnImputerMode(columns=['Utilities','Condition1','Condition2','OverallQual','OverallCond','YearRemodAdd','SaleCondition', 'Utilities'])),
    ('getdummies', GetDummies(column_names=['Utilities','Condition1','Condition2','OverallQual','OverallCond','YearRemodAdd','SaleCondition', 'Utilities']))])
    #('featuredropper', FeatureDropper())])

In [204]:
housing_train_data = pipeline.fit_transform(housing_train_data)

C:\Users\Auditor\anaconda3\lib\site-packages\pandas\core\algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)

In [205]:
housing_train_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,Utilities_AllPub,Utilities_NoSeWa,Utilities_AllPub,Utilities_NoSeWa
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,FR2,...,0,0,0,0,1,0,1,0,1,0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,Corner,...,1,0,0,0,0,0,1,0,1,0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,FR2,...,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0

In [206]:
housing_test_data = pipeline.fit_transform(housing_test_data)

C:\Users\Auditor\anaconda3\lib\site-packages\pandas\core\algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)

In [207]:
housing_test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,YearRemodAdd_2009,YearRemodAdd_2010,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,Utilities_AllPub,Utilities_AllPub
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,Corner,...,0,0,0,0,0,0,1,0,1,1
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,Inside,...,0,0,0,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,Inside,...,0,0,1,0,0,0,0,0,1,1
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,Inside,...,0,0,1,0,0,0,0,0,1,1
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1

In [208]:
# Get the intersection of column names
common_columns = housing_train_data.columns.intersection(housing_test_data.columns)

# Convert the common columns to a list
common_columns_list = common_columns.tolist()

# Display the list of common columns
print(common_columns_list)

['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 'BldgType', 'HouseStyle', 'YearBuilt', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'Utilities_AllPub', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'OverallQual_1', 'OverallQual_2', 'OverallQual_3', 'OverallQual_4', 'OverallQual_5', 'OverallQual_6', 'OverallQual_7', 'OverallQual_8', 'OverallQual_9', 'OverallQual_10', 'OverallCond_1', 'OverallCond_2', 'OverallCond_3', 'OverallCond_4', 'OverallCond_5', 'OverallCond_6', 'OverallCond_7', 'OverallCond_8', 'OverallCond_9', 'YearRemodAdd_1950', 'YearRemodAdd_1951', 'YearRemodAdd_1952', 'YearRemodAdd_1953', 'YearRemodAdd_1954', 'YearRemodAdd_1955', 'YearRemodAdd_1956', 'YearRemodAdd_1957', 'YearRemodAdd_1958', 'YearRemodAdd_1959', 'YearRemodAdd_1960', 'YearRemodAdd_1961', 'YearRemodAdd_1962', 'YearRemodAdd_1963', 'YearRemodAdd_1964', 'YearRemodAdd_1965', 'YearRemodAdd_1966', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1969', 'YearRemodAdd_1970', 'YearRemodAdd_1971', 'YearRemodAdd_1972', 'YearRemodAdd_1973', 'YearRemodAdd_1974', 'YearRemodAdd_1975', 'YearRemodAdd_1976', 'YearRemodAdd_1977', 'YearRemodAdd_1978', 'YearRemodAdd_1979', 'YearRemodAdd_1980', 'YearRemodAdd_1981', 'YearRemodAdd_1982', 'YearRemodAdd_1983', 'YearRemodAdd_1984', 'YearRemodAdd_1985', 'YearRemodAdd_1986', 'YearRemodAdd_1987', 'YearRemodAdd_1988', 'YearRemodAdd_1989', 'YearRemodAdd_1990', 'YearRemodAdd_1991', 'YearRemodAdd_1992', 'YearRemodAdd_1993', 'YearRemodAdd_1994', 'YearRemodAdd_1995', 'YearRemodAdd_1996', 'YearRemodAdd_1997', 'YearRemodAdd_1998', 'YearRemodAdd_1999', 'YearRemodAdd_2000', 'YearRemodAdd_2001', 'YearRemodAdd_2002', 'YearRemodAdd_2003', 'YearRemodAdd_2004', 'YearRemodAdd_2005', 'YearRemodAdd_2006', 'YearRemodAdd_2007', 'YearRemodAdd_2008', 'YearRemodAdd_2009', 'YearRemodAdd_2010', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial']

In [209]:
housing_train_data=housing_train_data[['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 'BldgType', 'HouseStyle', 'YearBuilt', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'Utilities_AllPub', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'OverallQual_1', 'OverallQual_2', 'OverallQual_3', 'OverallQual_4', 'OverallQual_5', 'OverallQual_6', 'OverallQual_7', 'OverallQual_8', 'OverallQual_9', 'OverallQual_10', 'OverallCond_1', 'OverallCond_2', 'OverallCond_3', 'OverallCond_4', 'OverallCond_5', 'OverallCond_6', 'OverallCond_7', 'OverallCond_8', 'OverallCond_9', 'YearRemodAdd_1950', 'YearRemodAdd_1951', 'YearRemodAdd_1952', 'YearRemodAdd_1953', 'YearRemodAdd_1954', 'YearRemodAdd_1955', 'YearRemodAdd_1956', 'YearRemodAdd_1957', 'YearRemodAdd_1958', 'YearRemodAdd_1959', 'YearRemodAdd_1960', 'YearRemodAdd_1961', 'YearRemodAdd_1962', 'YearRemodAdd_1963', 'YearRemodAdd_1964', 'YearRemodAdd_1965', 'YearRemodAdd_1966', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1969', 'YearRemodAdd_1970', 'YearRemodAdd_1971', 'YearRemodAdd_1972', 'YearRemodAdd_1973', 'YearRemodAdd_1974', 'YearRemodAdd_1975', 'YearRemodAdd_1976', 'YearRemodAdd_1977', 'YearRemodAdd_1978', 'YearRemodAdd_1979', 'YearRemodAdd_1980', 'YearRemodAdd_1981', 'YearRemodAdd_1982', 'YearRemodAdd_1983', 'YearRemodAdd_1984', 'YearRemodAdd_1985', 'YearRemodAdd_1986', 'YearRemodAdd_1987', 'YearRemodAdd_1988', 'YearRemodAdd_1989', 'YearRemodAdd_1990', 'YearRemodAdd_1991', 'YearRemodAdd_1992', 'YearRemodAdd_1993', 'YearRemodAdd_1994', 'YearRemodAdd_1995', 'YearRemodAdd_1996', 'YearRemodAdd_1997', 'YearRemodAdd_1998', 'YearRemodAdd_1999', 'YearRemodAdd_2000', 'YearRemodAdd_2001', 'YearRemodAdd_2002', 'YearRemodAdd_2003', 'YearRemodAdd_2004', 'YearRemodAdd_2005', 'YearRemodAdd_2006', 'YearRemodAdd_2007', 'YearRemodAdd_2008', 'YearRemodAdd_2009', 'YearRemodAdd_2010', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial','SalePrice']
]

In [210]:
housing_test_data[['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 'BldgType', 'HouseStyle', 'YearBuilt', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'Utilities_AllPub', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'OverallQual_1', 'OverallQual_2', 'OverallQual_3', 'OverallQual_4', 'OverallQual_5', 'OverallQual_6', 'OverallQual_7', 'OverallQual_8', 'OverallQual_9', 'OverallQual_10', 'OverallCond_1', 'OverallCond_2', 'OverallCond_3', 'OverallCond_4', 'OverallCond_5', 'OverallCond_6', 'OverallCond_7', 'OverallCond_8', 'OverallCond_9', 'YearRemodAdd_1950', 'YearRemodAdd_1951', 'YearRemodAdd_1952', 'YearRemodAdd_1953', 'YearRemodAdd_1954', 'YearRemodAdd_1955', 'YearRemodAdd_1956', 'YearRemodAdd_1957', 'YearRemodAdd_1958', 'YearRemodAdd_1959', 'YearRemodAdd_1960', 'YearRemodAdd_1961', 'YearRemodAdd_1962', 'YearRemodAdd_1963', 'YearRemodAdd_1964', 'YearRemodAdd_1965', 'YearRemodAdd_1966', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1969', 'YearRemodAdd_1970', 'YearRemodAdd_1971', 'YearRemodAdd_1972', 'YearRemodAdd_1973', 'YearRemodAdd_1974', 'YearRemodAdd_1975', 'YearRemodAdd_1976', 'YearRemodAdd_1977', 'YearRemodAdd_1978', 'YearRemodAdd_1979', 'YearRemodAdd_1980', 'YearRemodAdd_1981', 'YearRemodAdd_1982', 'YearRemodAdd_1983', 'YearRemodAdd_1984', 'YearRemodAdd_1985', 'YearRemodAdd_1986', 'YearRemodAdd_1987', 'YearRemodAdd_1988', 'YearRemodAdd_1989', 'YearRemodAdd_1990', 'YearRemodAdd_1991', 'YearRemodAdd_1992', 'YearRemodAdd_1993', 'YearRemodAdd_1994', 'YearRemodAdd_1995', 'YearRemodAdd_1996', 'YearRemodAdd_1997', 'YearRemodAdd_1998', 'YearRemodAdd_1999', 'YearRemodAdd_2000', 'YearRemodAdd_2001', 'YearRemodAdd_2002', 'YearRemodAdd_2003', 'YearRemodAdd_2004', 'YearRemodAdd_2005', 'YearRemodAdd_2006', 'YearRemodAdd_2007', 'YearRemodAdd_2008', 'YearRemodAdd_2009', 'YearRemodAdd_2010', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial']
]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,YearRemodAdd_2007,YearRemodAdd_2008,YearRemodAdd_2009,YearRemodAdd_2010,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,0,1,0
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,Corner,...,0,0,0,0,0,0,0,0,1,0
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,0,0,1,0
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,0,0,1,0
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,Inside,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,0,1,0
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,0,0,0,0
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,0,0,0,0
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,0,1,0
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,0,1,0

In [211]:
housing_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 178 entries, Id to SalePrice
dtypes: float64(11), int64(24), object(39), uint8(104)
memory usage: 992.5+ KB

In [212]:
housing_test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Columns: 177 entries, Id to Utilities_AllPub
dtypes: float64(11), int64(23), object(39), uint8(104)
memory usage: 980.4+ KB

In [213]:
housing_train_columns = housing_train_data.shape[1]
housing_test_columns = housing_test_data.shape[1]

# Display the number of columns for each DataFrame
print("Number of columns in housing_train_data:", housing_train_columns)
print("Number of columns in housing_test_data:", housing_test_columns)

Number of columns in housing_train_data: 178
Number of columns in housing_test_data: 177

In [214]:
housing_train_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,YearRemodAdd_2008,YearRemodAdd_2009,YearRemodAdd_2010,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,1,0,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,FR2,...,0,0,0,0,0,0,0,1,0,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,0,1,0,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,Corner,...,0,0,0,1,0,0,0,0,0,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,FR2,...,0,0,0,0,0,0,0,1,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,1,0,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,1,0,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,1,0,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,1,0,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,0,1,0,147500

In [215]:
housing_test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,YearRemodAdd_2009,YearRemodAdd_2010,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,Utilities_AllPub,Utilities_AllPub
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,Corner,...,0,0,0,0,0,0,1,0,1,1
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,Inside,...,0,0,0,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,Inside,...,0,0,1,0,0,0,0,0,1,1
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,Inside,...,0,0,1,0,0,0,0,0,1,1
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1

In [216]:
#Next we remove all none object from both

In [217]:
housing_train_data = housing_train_data.select_dtypes(exclude='object')

In [218]:
housing_train_data

,Id,MSSubClass,LotFrontage,LotArea,YearBuilt,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,YearRemodAdd_2008,YearRemodAdd_2009,YearRemodAdd_2010,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice
0,1,60,65.0,8450,2003,196.0,706.0,0.0,150.0,856.0,...,0,0,0,0,0,0,0,1,0,208500
1,2,20,80.0,9600,1976,0.0,978.0,0.0,284.0,1262.0,...,0,0,0,0,0,0,0,1,0,181500
2,3,60,68.0,11250,2001,162.0,486.0,0.0,434.0,920.0,...,0,0,0,0,0,0,0,1,0,223500
3,4,70,60.0,9550,1915,0.0,216.0,0.0,540.0,756.0,...,0,0,0,1,0,0,0,0,0,140000
4,5,60,84.0,14260,2000,350.0,655.0,0.0,490.0,1145.0,...,0,0,0,0,0,0,0,1,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,1999,0.0,0.0,0.0,953.0,953.0,...,0,0,0,0,0,0,0,1,0,175000
1456,1457,20,85.0,13175,1978,119.0,790.0,163.0,589.0,1542.0,...,0,0,0,0,0,0,0,1,0,210000
1457,1458,70,66.0,9042,1941,0.0,275.0,0.0,877.0,1152.0,...,0,0,0,0,0,0,0,1,0,266500
1458,1459,20,68.0,9717,1950,0.0,49.0,1029.0,0.0,1078.0,...,0,0,0,0,0,0,0,1,0,142125
1459,1460,20,75.0,9937,1965,0.0,830.0,290.0,136.0,1256.0,...,0,0,0,0,0,0,0,1,0,147500

In [219]:
# Get all column names in a list
column_names = list(housing_train_data.columns)

# Print or use the list as needed
print("Column Names:", column_names)

Column Names: ['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'YearBuilt', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'Utilities_AllPub', 'Utilities_AllPub', 'Utilities_AllPub', 'Utilities_AllPub', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'OverallQual_1', 'OverallQual_2', 'OverallQual_3', 'OverallQual_4', 'OverallQual_5', 'OverallQual_6', 'OverallQual_7', 'OverallQual_8', 'OverallQual_9', 'OverallQual_10', 'OverallCond_1', 'OverallCond_2', 'OverallCond_3', 'OverallCond_4', 'OverallCond_5', 'OverallCond_6', 'OverallCond_7', 'OverallCond_8', 'OverallCond_9', 'YearRemodAdd_1950', 'YearRemodAdd_1951', 'YearRemodAdd_1952', 'YearRemodAdd_1953', 'YearRemodAdd_1954', 'YearRemodAdd_1955', 'YearRemodAdd_1956', 'YearRemodAdd_1957', 'YearRemodAdd_1958', 'YearRemodAdd_1959', 'YearRemodAdd_1960', 'YearRemodAdd_1961', 'YearRemodAdd_1962', 'YearRemodAdd_1963', 'YearRemodAdd_1964', 'YearRemodAdd_1965', 'YearRemodAdd_1966', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1969', 'YearRemodAdd_1970', 'YearRemodAdd_1971', 'YearRemodAdd_1972', 'YearRemodAdd_1973', 'YearRemodAdd_1974', 'YearRemodAdd_1975', 'YearRemodAdd_1976', 'YearRemodAdd_1977', 'YearRemodAdd_1978', 'YearRemodAdd_1979', 'YearRemodAdd_1980', 'YearRemodAdd_1981', 'YearRemodAdd_1982', 'YearRemodAdd_1983', 'YearRemodAdd_1984', 'YearRemodAdd_1985', 'YearRemodAdd_1986', 'YearRemodAdd_1987', 'YearRemodAdd_1988', 'YearRemodAdd_1989', 'YearRemodAdd_1990', 'YearRemodAdd_1991', 'YearRemodAdd_1992', 'YearRemodAdd_1993', 'YearRemodAdd_1994', 'YearRemodAdd_1995', 'YearRemodAdd_1996', 'YearRemodAdd_1997', 'YearRemodAdd_1998', 'YearRemodAdd_1999', 'YearRemodAdd_2000', 'YearRemodAdd_2001', 'YearRemodAdd_2002', 'YearRemodAdd_2003', 'YearRemodAdd_2004', 'YearRemodAdd_2005', 'YearRemodAdd_2006', 'YearRemodAdd_2007', 'YearRemodAdd_2008', 'YearRemodAdd_2009', 'YearRemodAdd_2010', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial', 'SalePrice']

In [220]:
housing_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 139 entries, Id to SalePrice
dtypes: float64(11), int64(24), uint8(104)
memory usage: 547.6 KB

In [221]:
housing_test_data = housing_test_data.select_dtypes(exclude='object')

In [222]:
# Get all column names in a list
column_names2 = list(housing_test_data.columns)

# Print or use the list as needed
print("Column Names2:", column_names2)

Column Names2: ['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'YearBuilt', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'Utilities_AllPub', 'Utilities_AllPub', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'OverallQual_1', 'OverallQual_2', 'OverallQual_3', 'OverallQual_4', 'OverallQual_5', 'OverallQual_6', 'OverallQual_7', 'OverallQual_8', 'OverallQual_9', 'OverallQual_10', 'OverallCond_1', 'OverallCond_2', 'OverallCond_3', 'OverallCond_4', 'OverallCond_5', 'OverallCond_6', 'OverallCond_7', 'OverallCond_8', 'OverallCond_9', 'YearRemodAdd_1950', 'YearRemodAdd_1951', 'YearRemodAdd_1952', 'YearRemodAdd_1953', 'YearRemodAdd_1954', 'YearRemodAdd_1955', 'YearRemodAdd_1956', 'YearRemodAdd_1957', 'YearRemodAdd_1958', 'YearRemodAdd_1959', 'YearRemodAdd_1960', 'YearRemodAdd_1961', 'YearRemodAdd_1962', 'YearRemodAdd_1963', 'YearRemodAdd_1964', 'YearRemodAdd_1965', 'YearRemodAdd_1966', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1969', 'YearRemodAdd_1970', 'YearRemodAdd_1971', 'YearRemodAdd_1972', 'YearRemodAdd_1973', 'YearRemodAdd_1974', 'YearRemodAdd_1975', 'YearRemodAdd_1976', 'YearRemodAdd_1977', 'YearRemodAdd_1978', 'YearRemodAdd_1979', 'YearRemodAdd_1980', 'YearRemodAdd_1981', 'YearRemodAdd_1982', 'YearRemodAdd_1983', 'YearRemodAdd_1984', 'YearRemodAdd_1985', 'YearRemodAdd_1986', 'YearRemodAdd_1987', 'YearRemodAdd_1988', 'YearRemodAdd_1989', 'YearRemodAdd_1990', 'YearRemodAdd_1991', 'YearRemodAdd_1992', 'YearRemodAdd_1993', 'YearRemodAdd_1994', 'YearRemodAdd_1995', 'YearRemodAdd_1996', 'YearRemodAdd_1997', 'YearRemodAdd_1998', 'YearRemodAdd_1999', 'YearRemodAdd_2000', 'YearRemodAdd_2001', 'YearRemodAdd_2002', 'YearRemodAdd_2003', 'YearRemodAdd_2004', 'YearRemodAdd_2005', 'YearRemodAdd_2006', 'YearRemodAdd_2007', 'YearRemodAdd_2008', 'YearRemodAdd_2009', 'YearRemodAdd_2010', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial', 'Utilities_AllPub', 'Utilities_AllPub']

In [223]:
# Get common columns between the two DataFrames
common_columns = list(set(housing_train_data.columns) & set(housing_test_data.columns))

# Print or use the list as needed
print("Common Columns:", common_columns)

Common Columns: ['YearRemodAdd_1995', 'MoSold', 'YearRemodAdd_2006', 'YearRemodAdd_1998', 'OverallCond_8', 'Condition1_RRAn', 'YearRemodAdd_1954', 'YearRemodAdd_1985', 'YearRemodAdd_1958', 'GrLivArea', 'GarageArea', 'YearRemodAdd_1979', 'YrSold', 'YearRemodAdd_1961', 'MiscVal', 'YearRemodAdd_1986', 'YearRemodAdd_1963', 'OverallQual_5', 'YearRemodAdd_1969', 'MSSubClass', 'YearRemodAdd_1956', 'YearRemodAdd_1960', 'YearRemodAdd_1976', 'YearRemodAdd_1966', 'HalfBath', 'PoolArea', 'YearRemodAdd_1951', 'SaleCondition_Abnorml', 'LotFrontage', 'OpenPorchSF', '3SsnPorch', 'YearRemodAdd_1989', 'Condition2_Feedr', 'YearRemodAdd_1982', 'SaleCondition_Alloca', 'BsmtHalfBath', 'Condition1_RRNn', 'YearRemodAdd_2003', 'Condition2_Artery', 'TotalBsmtSF', 'YearRemodAdd_1971', 'WoodDeckSF', 'OverallQual_9', 'YearRemodAdd_1975', 'GarageCars', 'OverallCond_2', 'SaleCondition_Family', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1996', 'YearRemodAdd_1952', 'YearRemodAdd_1988', 'OverallCond_4', 'BsmtFinSF1', 'BsmtUnfSF', 'YearBuilt', 'GarageYrBlt', 'Condition2_PosA', 'YearRemodAdd_1978', 'YearRemodAdd_1993', 'OverallCond_9', 'YearRemodAdd_2008', 'SaleCondition_Normal', 'YearRemodAdd_2001', 'OverallQual_3', 'Condition1_Artery', 'YearRemodAdd_2002', 'Condition1_PosA', 'YearRemodAdd_1972', 'FullBath', 'KitchenAbvGr', 'OverallQual_8', 'YearRemodAdd_2007', 'Id', 'YearRemodAdd_1991', 'YearRemodAdd_1950', 'YearRemodAdd_1974', 'Fireplaces', 'LowQualFinSF', 'Condition1_Feedr', 'EnclosedPorch', 'YearRemodAdd_1980', 'Condition1_PosN', 'YearRemodAdd_1957', 'OverallQual_7', 'LotArea', 'OverallQual_6', 'BsmtFinSF2', 'YearRemodAdd_1992', 'YearRemodAdd_2004', 'YearRemodAdd_1983', 'Condition2_Norm', 'OverallQual_2', 'YearRemodAdd_1965', 'YearRemodAdd_1984', 'SaleCondition_AdjLand', 'SaleCondition_Partial', 'OverallQual_10', 'Condition1_RRNe', 'OverallCond_3', 'YearRemodAdd_1953', 'BsmtFullBath', 'YearRemodAdd_1990', 'YearRemodAdd_1997', 'YearRemodAdd_1964', 'YearRemodAdd_1970', 'BedroomAbvGr', 'YearRemodAdd_1959', 'YearRemodAdd_1962', 'OverallCond_1', 'YearRemodAdd_1999', 'OverallQual_4', 'YearRemodAdd_2010', 'OverallCond_5', 'YearRemodAdd_1977', 'YearRemodAdd_1994', 'YearRemodAdd_1955', 'MasVnrArea', 'Condition1_Norm', 'Utilities_AllPub', 'OverallQual_1', '1stFlrSF', 'Condition2_PosN', 'YearRemodAdd_1987', 'YearRemodAdd_2000', '2ndFlrSF', 'YearRemodAdd_1973', 'OverallCond_7', 'Condition1_RRAe', 'OverallCond_6', 'YearRemodAdd_2009', 'ScreenPorch', 'YearRemodAdd_2005', 'TotRmsAbvGrd', 'YearRemodAdd_1981']

In [224]:
housing_train_data= housing_train_data[['YearRemodAdd_1995', 'MoSold', 'YearRemodAdd_2006', 'YearRemodAdd_1998', 'OverallCond_8', 'Condition1_RRAn', 'YearRemodAdd_1954', 'YearRemodAdd_1985', 'YearRemodAdd_1958', 'GrLivArea', 'GarageArea', 'YearRemodAdd_1979', 'YrSold', 'YearRemodAdd_1961', 'MiscVal', 'YearRemodAdd_1986', 'YearRemodAdd_1963', 'OverallQual_5', 'YearRemodAdd_1969', 'MSSubClass', 'YearRemodAdd_1956', 'YearRemodAdd_1960', 'YearRemodAdd_1976', 'YearRemodAdd_1966', 'HalfBath', 'PoolArea', 'YearRemodAdd_1951', 'SaleCondition_Abnorml', 'LotFrontage', 'OpenPorchSF', '3SsnPorch', 'YearRemodAdd_1989', 'Condition2_Feedr', 'YearRemodAdd_1982', 'SaleCondition_Alloca', 'BsmtHalfBath', 'Condition1_RRNn', 'YearRemodAdd_2003', 'Condition2_Artery', 'TotalBsmtSF', 'YearRemodAdd_1971', 'WoodDeckSF', 'OverallQual_9', 'YearRemodAdd_1975', 'GarageCars', 'OverallCond_2', 'SaleCondition_Family', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1996', 'YearRemodAdd_1952', 'YearRemodAdd_1988', 'OverallCond_4', 'BsmtFinSF1', 'BsmtUnfSF', 'YearBuilt', 'GarageYrBlt', 'Condition2_PosA', 'YearRemodAdd_1978', 'YearRemodAdd_1993', 'OverallCond_9', 'YearRemodAdd_2008', 'SaleCondition_Normal', 'YearRemodAdd_2001', 'OverallQual_3', 'Condition1_Artery', 'YearRemodAdd_2002', 'Condition1_PosA', 'YearRemodAdd_1972', 'FullBath', 'KitchenAbvGr', 'OverallQual_8', 'YearRemodAdd_2007', 'Id', 'YearRemodAdd_1991', 'YearRemodAdd_1950', 'YearRemodAdd_1974', 'Fireplaces', 'LowQualFinSF', 'Condition1_Feedr', 'EnclosedPorch', 'YearRemodAdd_1980', 'Condition1_PosN', 'YearRemodAdd_1957', 'OverallQual_7', 'LotArea', 'OverallQual_6', 'BsmtFinSF2', 'YearRemodAdd_1992', 'YearRemodAdd_2004', 'YearRemodAdd_1983', 'Condition2_Norm', 'OverallQual_2', 'YearRemodAdd_1965', 'YearRemodAdd_1984', 'SaleCondition_AdjLand', 'SaleCondition_Partial', 'OverallQual_10', 'Condition1_RRNe', 'OverallCond_3', 'YearRemodAdd_1953', 'BsmtFullBath', 'YearRemodAdd_1990', 'YearRemodAdd_1997', 'YearRemodAdd_1964', 'YearRemodAdd_1970', 'BedroomAbvGr', 'YearRemodAdd_1959', 'YearRemodAdd_1962', 'OverallCond_1', 'YearRemodAdd_1999', 'OverallQual_4', 'YearRemodAdd_2010', 'OverallCond_5', 'YearRemodAdd_1977', 'YearRemodAdd_1994', 'YearRemodAdd_1955', 'MasVnrArea', 'Condition1_Norm', 'Utilities_AllPub', 'OverallQual_1', '1stFlrSF', 'Condition2_PosN', 'YearRemodAdd_1987', 'YearRemodAdd_2000', '2ndFlrSF', 'YearRemodAdd_1973', 'OverallCond_7', 'Condition1_RRAe', 'OverallCond_6', 'YearRemodAdd_2009', 'ScreenPorch', 'YearRemodAdd_2005', 'TotRmsAbvGrd', 'YearRemodAdd_1981','SalePrice']]

In [225]:
housing_train_data

,YearRemodAdd_1995,MoSold,YearRemodAdd_2006,YearRemodAdd_1998,OverallCond_8,Condition1_RRAn,YearRemodAdd_1954,YearRemodAdd_1985,YearRemodAdd_1958,GrLivArea,...,YearRemodAdd_1973,OverallCond_7,Condition1_RRAe,OverallCond_6,YearRemodAdd_2009,ScreenPorch,YearRemodAdd_2005,TotRmsAbvGrd,YearRemodAdd_1981,SalePrice
0,0,2,0,0,0,0,0,0,0,1710,...,0,0,0,0,0,0,0,8,0,208500
1,0,5,0,0,1,0,0,0,0,1262,...,0,0,0,0,0,0,0,6,0,181500
2,0,9,0,0,0,0,0,0,0,1786,...,0,0,0,0,0,0,0,6,0,223500
3,0,2,0,0,0,0,0,0,0,1717,...,0,0,0,0,0,0,0,7,0,140000
4,0,12,0,0,0,0,0,0,0,2198,...,0,0,0,0,0,0,0,9,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,8,0,0,0,0,0,0,0,1647,...,0,0,0,0,0,0,0,7,0,175000
1456,0,2,0,0,0,0,0,0,0,2073,...,0,0,0,1,0,0,0,7,0,210000
1457,0,5,1,0,0,0,0,0,0,2340,...,0,0,0,0,0,0,0,9,0,266500
1458,0,4,0,0,0,0,0,0,0,1078,...,0,0,0,1,0,0,0,5,0,142125
1459,0,6,0,0,0,0,0,0,0,1256,...,0,0,0,1,0,0,0,6,0,147500

In [226]:
housing_test_data = housing_test_data[['YearRemodAdd_1995', 'MoSold', 'YearRemodAdd_2006', 'YearRemodAdd_1998', 'OverallCond_8', 'Condition1_RRAn', 'YearRemodAdd_1954', 'YearRemodAdd_1985', 'YearRemodAdd_1958', 'GrLivArea', 'GarageArea', 'YearRemodAdd_1979', 'YrSold', 'YearRemodAdd_1961', 'MiscVal', 'YearRemodAdd_1986', 'YearRemodAdd_1963', 'OverallQual_5', 'YearRemodAdd_1969', 'MSSubClass', 'YearRemodAdd_1956', 'YearRemodAdd_1960', 'YearRemodAdd_1976', 'YearRemodAdd_1966', 'HalfBath', 'PoolArea', 'YearRemodAdd_1951', 'SaleCondition_Abnorml', 'LotFrontage', 'OpenPorchSF', '3SsnPorch', 'YearRemodAdd_1989', 'Condition2_Feedr', 'YearRemodAdd_1982', 'SaleCondition_Alloca', 'BsmtHalfBath', 'Condition1_RRNn', 'YearRemodAdd_2003', 'Condition2_Artery', 'TotalBsmtSF', 'YearRemodAdd_1971', 'WoodDeckSF', 'OverallQual_9', 'YearRemodAdd_1975', 'GarageCars', 'OverallCond_2', 'SaleCondition_Family', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1996', 'YearRemodAdd_1952', 'YearRemodAdd_1988', 'OverallCond_4', 'BsmtFinSF1', 'BsmtUnfSF', 'YearBuilt', 'GarageYrBlt', 'Condition2_PosA', 'YearRemodAdd_1978', 'YearRemodAdd_1993', 'OverallCond_9', 'YearRemodAdd_2008', 'SaleCondition_Normal', 'YearRemodAdd_2001', 'OverallQual_3', 'Condition1_Artery', 'YearRemodAdd_2002', 'Condition1_PosA', 'YearRemodAdd_1972', 'FullBath', 'KitchenAbvGr', 'OverallQual_8', 'YearRemodAdd_2007', 'Id', 'YearRemodAdd_1991', 'YearRemodAdd_1950', 'YearRemodAdd_1974', 'Fireplaces', 'LowQualFinSF', 'Condition1_Feedr', 'EnclosedPorch', 'YearRemodAdd_1980', 'Condition1_PosN', 'YearRemodAdd_1957', 'OverallQual_7', 'LotArea', 'OverallQual_6', 'BsmtFinSF2', 'YearRemodAdd_1992', 'YearRemodAdd_2004', 'YearRemodAdd_1983', 'Condition2_Norm', 'OverallQual_2', 'YearRemodAdd_1965', 'YearRemodAdd_1984', 'SaleCondition_AdjLand', 'SaleCondition_Partial', 'OverallQual_10', 'Condition1_RRNe', 'OverallCond_3', 'YearRemodAdd_1953', 'BsmtFullBath', 'YearRemodAdd_1990', 'YearRemodAdd_1997', 'YearRemodAdd_1964', 'YearRemodAdd_1970', 'BedroomAbvGr', 'YearRemodAdd_1959', 'YearRemodAdd_1962', 'OverallCond_1', 'YearRemodAdd_1999', 'OverallQual_4', 'YearRemodAdd_2010', 'OverallCond_5', 'YearRemodAdd_1977', 'YearRemodAdd_1994', 'YearRemodAdd_1955', 'MasVnrArea', 'Condition1_Norm', 'Utilities_AllPub', 'OverallQual_1', '1stFlrSF', 'Condition2_PosN', 'YearRemodAdd_1987', 'YearRemodAdd_2000', '2ndFlrSF', 'YearRemodAdd_1973', 'OverallCond_7', 'Condition1_RRAe', 'OverallCond_6', 'YearRemodAdd_2009', 'ScreenPorch', 'YearRemodAdd_2005', 'TotRmsAbvGrd', 'YearRemodAdd_1981']]

In [227]:
housing_test_data

,YearRemodAdd_1995,MoSold,YearRemodAdd_2006,YearRemodAdd_1998,OverallCond_8,Condition1_RRAn,YearRemodAdd_1954,YearRemodAdd_1985,YearRemodAdd_1958,GrLivArea,...,2ndFlrSF,YearRemodAdd_1973,OverallCond_7,Condition1_RRAe,OverallCond_6,YearRemodAdd_2009,ScreenPorch,YearRemodAdd_2005,TotRmsAbvGrd,YearRemodAdd_1981
0,0,6,0,0,0,0,0,0,0,896,...,0,0,0,0,1,0,120,0,5,0
1,0,6,0,0,0,0,0,0,1,1329,...,0,0,0,0,1,0,0,0,6,0
2,0,3,0,1,0,0,0,0,0,1629,...,701,0,0,0,0,0,0,0,6,0
3,0,6,0,1,0,0,0,0,0,1604,...,678,0,0,0,1,0,0,0,7,0
4,0,1,0,0,0,0,0,0,0,1280,...,0,0,0,0,0,0,144,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0,6,0,0,0,0,0,0,0,1092,...,546,0,1,0,0,0,0,0,5,0
1455,0,4,0,0,0,0,0,0,0,1092,...,546,0,0,0,0,0,0,0,6,0
1456,0,9,0,0,0,0,0,0,0,1224,...,0,0,1,0,0,0,0,0,7,0
1457,0,7,0,0,0,0,0,0,0,970,...,0,0,0,0,0,0,0,0,6,0
1458,0,11,0,0,0,0,0,0,0,2000,...,1004,0,0,0,0,0,0,0,9,0

In [228]:
housing_test_data

,YearRemodAdd_1995,MoSold,YearRemodAdd_2006,YearRemodAdd_1998,OverallCond_8,Condition1_RRAn,YearRemodAdd_1954,YearRemodAdd_1985,YearRemodAdd_1958,GrLivArea,...,2ndFlrSF,YearRemodAdd_1973,OverallCond_7,Condition1_RRAe,OverallCond_6,YearRemodAdd_2009,ScreenPorch,YearRemodAdd_2005,TotRmsAbvGrd,YearRemodAdd_1981
0,0,6,0,0,0,0,0,0,0,896,...,0,0,0,0,1,0,120,0,5,0
1,0,6,0,0,0,0,0,0,1,1329,...,0,0,0,0,1,0,0,0,6,0
2,0,3,0,1,0,0,0,0,0,1629,...,701,0,0,0,0,0,0,0,6,0
3,0,6,0,1,0,0,0,0,0,1604,...,678,0,0,0,1,0,0,0,7,0
4,0,1,0,0,0,0,0,0,0,1280,...,0,0,0,0,0,0,144,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0,6,0,0,0,0,0,0,0,1092,...,546,0,1,0,0,0,0,0,5,0
1455,0,4,0,0,0,0,0,0,0,1092,...,546,0,0,0,0,0,0,0,6,0
1456,0,9,0,0,0,0,0,0,0,1224,...,0,0,1,0,0,0,0,0,7,0
1457,0,7,0,0,0,0,0,0,0,970,...,0,0,0,0,0,0,0,0,6,0
1458,0,11,0,0,0,0,0,0,0,2000,...,1004,0,0,0,0,0,0,0,9,0

In [229]:
housing_test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Columns: 138 entries, YearRemodAdd_1995 to YearRemodAdd_1981
dtypes: float64(11), int64(23), uint8(104)
memory usage: 535.9 KB

# Import necessary libraries

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor  # You can choose a different model based on your problem

# Assuming the target variable (what you want to predict) is in the 'target_column' column
#target_column = 'SalePrice'

# Separate features and target variable in the training data
X_train = housing_train_data.drop('SalePrice', axis=1)
y_train = housing_train_data['SalePrice']

# Split the training data into train and validation sets
#X_train_split, X_val, y_train_split, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=1)


# Choose a machine learning model (Random Forest Regressor in this example)
rf = RandomForestRegressor()

# Fit the model on the training split
rf.fit(X_train, y_train)

# Make predictions on the validation set
#val_predictions = model.predict(X_val)

# Evaluate the model performance on the validation set if needed
# You may use metrics like Mean Absolute Error, Mean Squared Error, etc.

# Once satisfied with the model, make predictions on the test data
test_predictions = model.predict(housing_test_data)

In [267]:
from sklearn.preprocessing import StandardScaler

X = housing_train_data.drop(['SalePrice'], axis=1)
y = housing_train_data['SalePrice']

scaler = StandardScaler()
X_data = scaler.fit_transform(X)
y_data = y.to_numpy()

In [268]:
#Creating a function with many machine learning models

def models (X_train, y_train):
    
    #Use Logistic Regression
    from sklearn.linear_model import LogisticRegression
    log = LogisticRegression(random_state=0)
    log.fit(X_train, y_train)
    
    #Use KNeighnours
    from sklearn.neighbors import KNeighborsClassifier
    knn = KNeighborsClassifier(n_neighbors=5, metric= 'minkowski', p=2)
    knn.fit(X_train, y_train)
    
    #Use SVC (linear Kernel)
    from sklearn.svm import SVC
    svc_lin = SVC(kernel='linear', random_state=0)
    svc_lin.fit(X_train, y_train)
    
    #Use SVC (RBF Kernel)
    from sklearn.svm import SVC
    svc_rbf = SVC(kernel='rbf', random_state=0)
    svc_rbf.fit(X_train, y_train)
    
    #Use Gaussian NB
    from sklearn.naive_bayes import GaussianNB
    gauss = GaussianNB()
    gauss.fit(X_train, y_train)
    
    #Use Decision Tree
    from sklearn.tree import DecisionTreeClassifier
    tree = DecisionTreeClassifier(criterion='entropy', random_state=0)
    tree.fit(X_train, y_train)
    
    
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.model_selection import GridSearchCV

    # Instantiate RandomForestClassifier
    forest = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
    forest.fit(X_train, y_train)

    #Print the training accuracy for each model
    print('[0]Logistic Regression Training Accuracy: ', log.score(X_train, y_train))
    print('[1]K Neighborys Training Accuracy: ', knn.score(X_train, y_train))
    print('[2]SVC Linear Training Accuracy: ', svc_lin.score(X_train, y_train))
    print('[3]SVC RBFTraining Accuracy: ', svc_rbf.score(X_train, y_train))
    print('[4]Gaussian NB Training Accuracy: ', gauss.score(X_train, y_train))
    print('[5]Decision Tree Training Accuracy: ', tree.score(X_train, y_train))
    print('[6]Random Forest Training Accuracy: ', forest.score(X_train, y_train))

    return log, knn, svc_lin, svc_rbf, gauss, tree, forest

In [269]:
model = models(X_train, y_train)

C:\Users\Auditor\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[0]Logistic Regression Training Accuracy:  0.2797319932998325
[1]K Neighborys Training Accuracy:  0.19765494137353434
[2]SVC Linear Training Accuracy:  1.0
[3]SVC RBFTraining Accuracy:  0.02512562814070352
[4]Gaussian NB Training Accuracy:  0.9179229480737019
[5]Decision Tree Training Accuracy:  1.0
[6]Random Forest Training Accuracy:  1.0

In [270]:
#Use SVC
from sklearn.svm import SVC

svc_lin = SVC()

svc_lin.fit(X_train, y_train)

from sklearn.linear_model import LogisticRegression

svc_lin.fit(X_train, y_train)

y_pred = svc_lin.predict(X_test)

accuracy = svc_lin.score(X_test, y_test)

print(f"Accuracy: {accuracy}")

Accuracy: 0.02666666666666667

In [271]:
predictions_svc = svc_lin.predict(housing_test_data)

In [272]:
predictions_svc

array([155000, 155000, 155000, ..., 145000, 155000, 155000], dtype=int64)

In [273]:
final_df = pd.DataFrame(housing_test_data['Id'])
final_df['SalePrice'] = predictions_svc
final_df.to_csv('Downloads/CaliforniaHousingsvc_svc.csv', index =False)

In [274]:
final_df

        Id  SalePrice
0     1461     155000
1     1462     155000
2     1463     155000
3     1464     155000
4     1465     155000
...    ...        ...
1454  2915     155000
1455  2916     155000
1456  2917     145000
1457  2918     155000
1458  2919     155000

[1459 rows x 2 columns]

In [275]:
len(test_predictions)

1459

In [276]:
from sklearn.model_selection import train_test_split

from sklearn.svm import SVC

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=1)

svc_lin = SVC(kernel='linear', random_state=0)
svc_lin.fit(X_train, y_train)

y_pred = svc_lin.predict(X_test)

accuracy = svc_lin.score(X_test, y_test)

print(f"Accuracy: {accuracy}")

Accuracy: 0.008333333333333333

In [288]:
predictions_svc_lin = svc_lin.predict(housing_test_data)

In [289]:
final_df = pd.DataFrame(housing_test_data['Id'])
final_df['SalePrice'] = predictions_svc_lin
final_df.to_csv('Downloads/CaliforniaHousingsvc.csv', index =False)

In [290]:
final_df

        Id  SalePrice
0     1461     146800
1     1462     256000
2     1463     190000
3     1464     171000
4     1465     181000
...    ...        ...
1454  2915      91500
1455  2916      91500
1456  2917      84500
1457  2918     111000
1458  2919     310000

[1459 rows x 2 columns]

In [281]:
# Once satisfied with the model, make predictions on the test data
test_predictions = model.predict(housing_test_data)

AttributeError: 'tuple' object has no attribute 'predict'

In [282]:
len(test_predictions)

1459

In [283]:
#final_df = pd.DataFrame(housing_test_data['Id'])
#final_df['SalePrice'] = rf
#final_df.to_csv('Downloads/CaliforniaHousingrf.csv', index =False)

In [284]:
#Use Gaussian NB
from sklearn.naive_bayes import GaussianNB
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=1)

gauss = GaussianNB()
gauss.fit(X_train, y_train)


gauss.fit(X_train, y_train)

y_pred = gauss.predict(X_test)

accuracy = svc_lin.score(X_test, y_test)

print(f"Accuracy: {accuracy}")

Accuracy: 0.32905982905982906

In [285]:
predictions_gauss = gauss.predict(housing_test_data)

In [286]:
predictions_gauss

array([144000, 190000, 215000, ..., 215000, 120000, 215000], dtype=int64)

In [287]:
final_df = pd.DataFrame(housing_test_data['Id'])
final_df['SalePrice'] = predictions_gauss
final_df.to_csv('Downloads/CaliforniaHousingGauss.csv', index =False)

In [278]:
final_df

        Id  SalePrice
0     1461     155000
1     1462     155000
2     1463     155000
3     1464     155000
4     1465     155000
...    ...        ...
1454  2915     155000
1455  2916     155000
1456  2917     145000
1457  2918     155000
1458  2919     155000

[1459 rows x 2 columns]

In [279]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\auditor\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\auditor\anaconda3\lib\site-packages (from xgboost) (1.22.0)
Requirement already satisfied: scipy in c:\users\auditor\anaconda3\lib\site-packages (from xgboost) (1.7.3)

In [291]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an XGBoost model
xgb_model = XGBRegressor()

# Fit the model on the training data
xgb_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = xgb_model.predict(X_test)

# Evaluate the model performance
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print(f'Mean Absolute Error (MAE): {mae}')
print(f'Mean Squared Error (MSE): {mse}')

ValueError: feature_names must be unique. Duplicates found: ['Utilities_AllPub']