In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
%matplotlib inline
print('Done!')

Done!

In [2]:
housing_train_data = pd.read_csv('C:\\Users\\Auditor\\Desktop\\Victor\\New folder\\Data Science\\Projects\\House Prices - Advanced Regression Techniques\\Train.csv')

In [4]:
housing_test_data = pd.read_csv('C:\\Users\\Auditor\\Desktop\\Victor\\New folder\\Data Science\\Projects\\House Prices - Advanced Regression Techniques\\Test.csv')

In [5]:
housing_train_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [6]:
housing_test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [7]:
housing_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [8]:
housing_test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [9]:
#X_train = housing_train_data.drop(['SalePrice'], axis=1)
#y_train = housing_train_data['SalePrice']

In [10]:
#X_train

In [11]:
#y_train

In [12]:
#We are going to create a pipeline that in one go: fills null values, drops unwanted columns and gets dummies/ one_hot_encoder

In [13]:
#Changing all null numeric values to mean

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer

class MultipleColumnImputerMean(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns):
        self.columns = columns
    
    def fit(self, X, y=None):
        self.imputer = SimpleImputer(strategy='mean')
        self.imputer.fit(X[self.columns])
        return self
    
    def transform(self, X):
        X_copy = X.copy()
        X_copy[self.columns] = self.imputer.transform(X_copy[self.columns])
        return X_copy

In [14]:
#Changing all null string values to mode

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer

class MultipleColumnImputerMode(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns):
        self.columns = columns
    
    def fit(self, X, y=None):
        self.imputer = SimpleImputer(strategy='most_frequent')
        self.imputer.fit(X[self.columns])
        return self
    
    def transform(self, X):
        X_copy = X.copy()
        X_copy[self.columns] = self.imputer.transform(X_copy[self.columns])
        return X_copy

In [15]:
#gets dummies/ one_hot_encoder
class GetDummies(BaseEstimator, TransformerMixin):
    
    def __init__(self, column_names):
        self.column_names = column_names

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        columns = X[self.column_names]  # Extract the specified columns

        # Apply one-hot encoding to each specified column
        dummies_list = [pd.get_dummies(columns[col], prefix=col) for col in self.column_names]

        # Concatenate one-hot encoded columns with the original DataFrame and delete dummied column
        X_encoded = pd.concat([X] + dummies_list, axis=1).drop(self.column_names, axis=1)

        return X_encoded

In [16]:
#Create a pipeline

In [17]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('MultipleColumnImputerMean', MultipleColumnImputerMean(columns=['LotFrontage', 'MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','BsmtFullBath','BsmtHalfBath','GarageYrBlt','GarageCars','GarageArea'])),
    ('MultipleColumnImputerMode', MultipleColumnImputerMode(columns=['Utilities','Condition1','Condition2','OverallQual','OverallCond','YearRemodAdd','SaleCondition', 'Utilities'])),
    ('getdummies', GetDummies(column_names=['Utilities','Condition1','Condition2','OverallQual','OverallCond','YearRemodAdd','SaleCondition', 'Utilities']))])
    #('featuredropper', FeatureDropper())])

In [18]:
housing_train_data = pipeline.fit_transform(housing_train_data)

C:\Users\Auditor\anaconda3\lib\site-packages\pandas\core\algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)

In [19]:
housing_train_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,Utilities_AllPub,Utilities_NoSeWa,Utilities_AllPub,Utilities_NoSeWa
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,FR2,...,0,0,0,0,1,0,1,0,1,0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,Corner,...,1,0,0,0,0,0,1,0,1,0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,FR2,...,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0

In [23]:
housing_train_data['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [24]:
housing_test_data = pipeline.fit_transform(housing_test_data)

KeyError: "None of [Index(['Utilities', 'Condition1', 'Condition2', 'OverallQual', 'OverallCond',\n       'YearRemodAdd', 'SaleCondition', 'Utilities'],\n      dtype='object')] are in the [columns]"

In [21]:
housing_test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,YearRemodAdd_2009,YearRemodAdd_2010,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,Utilities_AllPub,Utilities_AllPub
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,Corner,...,0,0,0,0,0,0,1,0,1,1
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,Inside,...,0,0,0,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,Inside,...,0,0,1,0,0,0,0,0,1,1
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,Inside,...,0,0,1,0,0,0,0,0,1,1
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,0,0,1,0,1,1

In [25]:
X_train = housing_train_data.drop(['SalePrice'], axis=1)
y_train = housing_train_data['SalePrice']

In [26]:
X_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,...,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,Utilities_AllPub,Utilities_NoSeWa,Utilities_AllPub,Utilities_NoSeWa
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,FR2,...,0,0,0,0,1,0,1,0,1,0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,Corner,...,1,0,0,0,0,0,1,0,1,0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,FR2,...,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,Inside,...,0,0,0,0,1,0,1,0,1,0

In [27]:
y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [ ]:
# Get the intersection of column names
common_columns = housing_train_data.columns.intersection(housing_test_data.columns)

# Convert the common columns to a list
common_columns_list = common_columns.tolist()

# Display the list of common columns
print(common_columns_list)

In [ ]:
housing_train_data[['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 'BldgType', 'HouseStyle', 'YearBuilt', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'Utilities_AllPub', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'OverallQual_1', 'OverallQual_2', 'OverallQual_3', 'OverallQual_4', 'OverallQual_5', 'OverallQual_6', 'OverallQual_7', 'OverallQual_8', 'OverallQual_9', 'OverallQual_10', 'OverallCond_1', 'OverallCond_2', 'OverallCond_3', 'OverallCond_4', 'OverallCond_5', 'OverallCond_6', 'OverallCond_7', 'OverallCond_8', 'OverallCond_9', 'YearRemodAdd_1950', 'YearRemodAdd_1951', 'YearRemodAdd_1952', 'YearRemodAdd_1953', 'YearRemodAdd_1954', 'YearRemodAdd_1955', 'YearRemodAdd_1956', 'YearRemodAdd_1957', 'YearRemodAdd_1958', 'YearRemodAdd_1959', 'YearRemodAdd_1960', 'YearRemodAdd_1961', 'YearRemodAdd_1962', 'YearRemodAdd_1963', 'YearRemodAdd_1964', 'YearRemodAdd_1965', 'YearRemodAdd_1966', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1969', 'YearRemodAdd_1970', 'YearRemodAdd_1971', 'YearRemodAdd_1972', 'YearRemodAdd_1973', 'YearRemodAdd_1974', 'YearRemodAdd_1975', 'YearRemodAdd_1976', 'YearRemodAdd_1977', 'YearRemodAdd_1978', 'YearRemodAdd_1979', 'YearRemodAdd_1980', 'YearRemodAdd_1981', 'YearRemodAdd_1982', 'YearRemodAdd_1983', 'YearRemodAdd_1984', 'YearRemodAdd_1985', 'YearRemodAdd_1986', 'YearRemodAdd_1987', 'YearRemodAdd_1988', 'YearRemodAdd_1989', 'YearRemodAdd_1990', 'YearRemodAdd_1991', 'YearRemodAdd_1992', 'YearRemodAdd_1993', 'YearRemodAdd_1994', 'YearRemodAdd_1995', 'YearRemodAdd_1996', 'YearRemodAdd_1997', 'YearRemodAdd_1998', 'YearRemodAdd_1999', 'YearRemodAdd_2000', 'YearRemodAdd_2001', 'YearRemodAdd_2002', 'YearRemodAdd_2003', 'YearRemodAdd_2004', 'YearRemodAdd_2005', 'YearRemodAdd_2006', 'YearRemodAdd_2007', 'YearRemodAdd_2008', 'YearRemodAdd_2009', 'YearRemodAdd_2010', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial']
]

In [ ]:
housing_test_data[['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 'BldgType', 'HouseStyle', 'YearBuilt', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'Utilities_AllPub', 'Condition1_Artery', 'Condition1_Feedr', 'Condition1_Norm', 'Condition1_PosA', 'Condition1_PosN', 'Condition1_RRAe', 'Condition1_RRAn', 'Condition1_RRNe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_Norm', 'Condition2_PosA', 'Condition2_PosN', 'OverallQual_1', 'OverallQual_2', 'OverallQual_3', 'OverallQual_4', 'OverallQual_5', 'OverallQual_6', 'OverallQual_7', 'OverallQual_8', 'OverallQual_9', 'OverallQual_10', 'OverallCond_1', 'OverallCond_2', 'OverallCond_3', 'OverallCond_4', 'OverallCond_5', 'OverallCond_6', 'OverallCond_7', 'OverallCond_8', 'OverallCond_9', 'YearRemodAdd_1950', 'YearRemodAdd_1951', 'YearRemodAdd_1952', 'YearRemodAdd_1953', 'YearRemodAdd_1954', 'YearRemodAdd_1955', 'YearRemodAdd_1956', 'YearRemodAdd_1957', 'YearRemodAdd_1958', 'YearRemodAdd_1959', 'YearRemodAdd_1960', 'YearRemodAdd_1961', 'YearRemodAdd_1962', 'YearRemodAdd_1963', 'YearRemodAdd_1964', 'YearRemodAdd_1965', 'YearRemodAdd_1966', 'YearRemodAdd_1967', 'YearRemodAdd_1968', 'YearRemodAdd_1969', 'YearRemodAdd_1970', 'YearRemodAdd_1971', 'YearRemodAdd_1972', 'YearRemodAdd_1973', 'YearRemodAdd_1974', 'YearRemodAdd_1975', 'YearRemodAdd_1976', 'YearRemodAdd_1977', 'YearRemodAdd_1978', 'YearRemodAdd_1979', 'YearRemodAdd_1980', 'YearRemodAdd_1981', 'YearRemodAdd_1982', 'YearRemodAdd_1983', 'YearRemodAdd_1984', 'YearRemodAdd_1985', 'YearRemodAdd_1986', 'YearRemodAdd_1987', 'YearRemodAdd_1988', 'YearRemodAdd_1989', 'YearRemodAdd_1990', 'YearRemodAdd_1991', 'YearRemodAdd_1992', 'YearRemodAdd_1993', 'YearRemodAdd_1994', 'YearRemodAdd_1995', 'YearRemodAdd_1996', 'YearRemodAdd_1997', 'YearRemodAdd_1998', 'YearRemodAdd_1999', 'YearRemodAdd_2000', 'YearRemodAdd_2001', 'YearRemodAdd_2002', 'YearRemodAdd_2003', 'YearRemodAdd_2004', 'YearRemodAdd_2005', 'YearRemodAdd_2006', 'YearRemodAdd_2007', 'YearRemodAdd_2008', 'YearRemodAdd_2009', 'YearRemodAdd_2010', 'SaleCondition_Abnorml', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal', 'SaleCondition_Partial']
]

In [ ]:
housing_train_data.info()

In [ ]:
housing_test_data.info()

In [ ]:
housing_train_columns = housing_train_data.shape[1]
housing_test_columns = housing_test_data.shape[1]

# Display the number of columns for each DataFrame
print("Number of columns in housing_train_data:", housing_train_columns)
print("Number of columns in housing_test_data:", housing_test_columns)

In [ ]:
common_columns = housing_train_data.columns.intersection(housing_test_data.columns)

# Filter DataFrames to keep only common columns in the same order
housing_train_data = housing_train_data[common_columns]
housing_test_data = housing_test_data[common_columns]

# Display the DataFrames with common columns
print("housing_train_data with common columns:")
print(housing_train_data_common.head())

print("\nhousing_test_data with common columns:")
print(housing_test_data_common.head())

In [ ]:
housing_train_data

In [ ]:
housing_train_data

In [ ]:
housing_train_data.info()

In [ ]:
housing_test_data.info()

In [ ]:
#Next we remove all none object from both

In [ ]:
housing_train_data = housing_train_data.select_dtypes(exclude='object')

In [ ]:
housing_test_data = housing_test_data.select_dtypes(exclude='object')

In [ ]:
housing_train_data

In [ ]:
housing_test_data